import Head from 'next/head'

// Static data fetching with revalidation.
async function fetchSessions() {
  const response = await fetch(
    "https://conferenceapi.azurewebsites.net/sessions",
    { next: { revalidate: 60 } }
  );

  const data = await response.json();
  return data;
}

// Static data fetching with revalidation.
async function fetchSpeakers() {
  const response = await fetch(
    "https://conferenceapi.azurewebsites.net/speakers",
    { next: { revalidate: 60 } }
  );

  const data = await response.json();
  return data;
}

// Static data fetching with revalidation.
async function fetchTopics() {
  const response = await fetch(
    "https://conferenceapi.azurewebsites.net/topics",
    { next: { revalidate: 60 } }
  );

  const data = await response.json();
  return data;
}

async function Home() {
  const sessions = await fetchSessions();
  //console.log(sessions.collection.items.length);
  const speakers = await fetchSpeakers();
  //console.log(speakers.collection.items.length);
  const topics = await fetchTopics();
  //console.log(topics.collection.items.length);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="flex flex-col md:flex-row lg:flex-row lg:my-16 md:my-16">
        <div data-aos='flip-left' data-aos-delay='500' class="lg:animate-pulse md:animate-pulse animate-none my-5 flex flex-col bg-black text-white opacity-70 h-48 lg:w-1/3 md:w-1/3 w-full lg:mx-14 md:mx-5 items-center justify-center rounded-md shadow-2xl">
          <div>
            <div class="text-3xl">Sessions</div>
          </div>
          <div>
            <span class="text-6xl">{sessions.collection.items.length}</span>
          </div>
        </div>
        <div data-aos='flip-left' data-aos-delay='300' class="lg:animate-pulse md:animate-pulse animate-none my-5 flex flex-col bg-black text-white opacity-70 h-48 lg:w-1/3 md:w-1/3 w-full lg:mx-14 md:mx-5 items-center justify-center rounded-md shadow-2xl">
          <div>
            <div class="text-3xl">Speakers</div>
          </div>
          <div>
            <span class="text-6xl">{speakers.collection.items.length}</span>
          </div>
        </div>
        <div data-aos='flip-left' data-aos-delay='100' class="lg:animate-pulse md:animate-pulse animate-none my-5 flex flex-col bg-black text-white opacity-70 h-48 lg:w-1/3 md:w-1/3 w-full lg:mx-14 md:mx-5 items-center justify-center rounded-md shadow-2xl">
          <div>
            <div class="text-3xl">Topics</div>
          </div>
          <div>
            <span class="text-6xl">{topics.collection.items.length}</span>
          </div>
        </div>
      </div>
    </>
  )
}

// // This function gets called at build time on server-side.
// // It may be called again, on a serverless function, if
// // revalidation is enabled and a new request comes in
// export async function getServerSideProps(context) {
//   console.log('Going inside...')
//   const sessionResponse = await fetch('https://conferenceapi.azurewebsites.net/sessions')
//   const sessions = await sessionResponse.json()
//   console.log(sessions);

//   const speakersResponse = await fetch('https://conferenceapi.azurewebsites.net/speakers')
//   const speakers = await speakersResponse.json()

//   const topicsResponse = await fetch('https://conferenceapi.azurewebsites.net/topics')
//   const topics = await topicsResponse.json()

//   return {
//     props: {
//       sessions,
//       speakers,
//       topics,
//     },
//     // Next.js will attempt to re-generate the page:
//     // - When a request comes in
//     // - At most once every 60 seconds
//     revalidate: 60, // In seconds
//   }
// }

export default Home;